export const USERS = [
    {
        id: "001",
        displayName: "Aislyn_Faeryn",
        fullName: "Aislyn Faeryn",
        age: 25,
        species: "Faeril",
        location: "Sylvalora",
        gender: "Femenino",
        magicClass: "Luminaris",
        description: "Una joven Faeril que domina la magia de la luz, conocida por su naturaleza empática y su búsqueda de la verdad.",
        dateOfUnion: "2023-10-17",
        profilePicture: "https://example.com/faeril.jpg",
    },
    {
        id: "002",
        displayName: "Kael_Thornezhar",
        fullName: "Kael Daegon",
        age: 30,
        species: "Daegon",
        location: "Thornez'har",
        gender: "Masculino",
        magicClass: "Aegiscaster",
        description: "Un guerrero Daegon del frío desierto de Thornez'har, conocido por su destreza con escudos mágicos y defensa impenetrable.",
        dateOfUnion: "2023-05-12",
        profilePicture: "https://example.com/daegon.jpg",
    },
    {
        id: "003",
        displayName: "Lyria_Nyssara",
        fullName: "Lyria Felyrian",
        age: 22,
        species: "Felyrian",
        location: "Nyssara",
        gender: "Femenino",
        magicClass: "Arcanomancer",
        description: "Una Felyrian de Nyssara, hábil en el control de arcanos y con una mente curiosa que explora las energías místicas.",
        dateOfUnion: "2024-01-03",
        profilePicture: "https://example.com/felyrian.jpg",
    },
    {
        id: "004",
        displayName: "Torin_Abyssor",
        fullName: "Torin Jebale-c",
        age: 40,
        species: "Jebale-c",
        location: "Abyssor",
        gender: "Masculino",
        magicClass: "Valkyros",
        description: "Torin es un enigmático Jebale-c de Abyssor, maestro de las tormentas y los vientos furiosos que guarda secretos ancestrales.",
        dateOfUnion: "2022-11-20",
        profilePicture: "https://example.com/jebale-c.jpg",
    }, {
        id: "005",
        displayName: "Eirik_Indawo",
        fullName: "Eirik Human",
        age: 35,
        species: "Human",
        location: "Centro de Indawo",
        gender: "Masculino",
        magicClass: "Arcanomancer",
        description: "Eirik, un humano del Centro de Indawo, es un hechicero con vasto conocimiento en las artes arcanas y estrategias mágicas.",
        dateOfUnion: "2021-08-15",
        profilePicture: "https://example.com/human.jpg",
    }
]